EXPERIMENT:
  name: "wo_emb_wo_label_w_pred"
  n_pred_vectors: [1,2,3,4,5]
  n_noise_samples: 0
  k_fold: 5


DATASET:
  names: ["gesture_phase", "adult", "heloc"]
  one_hot: true
  ratio: 0.2
  force: true
  shuffle: false
  baseline: "neural_network" # neural_network / xgboost
  feature_reduction:
#    method: "guassian"
    n_components: 10


CLOUD:
  name: "image" # tabular / ensemble / dense / image / resnet_embedding
  epochs: 10
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "neural_network" # xgboost / dense
  epochs: 10
  batch_size: 8
  dropout_rate: 0.3

ENCRYPTOR:
  name: "efficientnet" # dc / dense_complex / dense / resnet / efficientnet
