EXPERIMENT:
  name: "w_emb_w_label_w_pred"
  n_pred_vectors: 1
  n_noise_samples: 2
  k_fold: 1


DATASET:
  names: ["heloc"]#,"bank_marketing", "gesture_phase", "adult", "heloc"]
  one_hot: true
  ratio: 1
  force: true
  baseline: "neural_network" # neural_network / xgboost
  pd_dataframe: true

EMBEDDING:
  base_model: resnet50

CLOUD:
  name: "resnet" # tabular / ensemble / dense / efficientnet / resnet / casual_llm / masked_llm / sequence_classification_llm / patch
  epochs: 10
  top_k: 1000
  logits: false # True - Use LLM logits, False - Use llm's vocab probability
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "dense" # dense / xgboost
  epochs: 10
  batch_size: 8
  dropout_rate: 0.4

ENCRYPTOR:
  name: "resnet" # dc / dense / resnet / efficientnet
