EXPERIMENT:
  name: "w_emb_wo_label_w_pred"
  n_pred_vectors: 1
  n_noise_samples: 0
  k_fold: 5


DATASET:
  names: ["heloc"]#["gesture_phase", "adult", "heloc"]
  one_hot: false
  ratio: 0.2
  force: true
  baseline: "xgboost" # neural_network / xgboost
  pd_dataframe: true
#  feature_reduction:
##    method: "guassian"
#    n_components: 10


CLOUD:
  name: "tabular_llm" # tabular / ensemble / dense / efficientnet / resnet_embedding / tabular_llm
  epochs: 10
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "xgboost" # xgboost / dense
  epochs: 10
  batch_size: 8
  dropout_rate: 0.3

ENCRYPTOR:
  name: "resnet" # dc / dense_complex / dense / resnet / efficientnet
