EXPERIMENT:
  name: "w_emb_w_label"
  n_pred_vectors: 5
  n_noise_samples: 3


DATASET:
  names: ["heloc"]
  one_hot: false
  ratio: 0.2
  force: true


CLOUD:
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "xgboost"
