EXPERIMENT:
  name: "w_emb_w_label_w_pred"
  n_pred_vectors: 2
  n_noise_samples: 3
  k_fold: 5


DATASET:
  names: ["gesture_phase", "adult", "heloc"]
  one_hot: false
  ratio: 0.05
  force: true
  shuffle: false
  baseline: "neural_network" # neural_network / xgboost
  feature_reduction:
#    method: "guassian"
    n_components: 10


CLOUD:
  name: "ensemble" # tabular / ensemble / neural_network
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "dense" # xgboost / dense
  epochs: 10
  batch_size: 8
  dropout_rate: 0.3

ENCRYPTOR:
  name: "dense_complex" # dc / dense_complex / dense
