EXPERIMENT:
  name: "w_emb_w_label"
  n_pred_vectors: 1
  n_noise_samples: 1


DATASET:
  source: ""
  n_classes: 2
  one_hot: false
  ratio: 0.2


CLOUD:
  path: "gesture_phase_0.2_models.pkl"
  models: []

IIM:
  name: "xgboost"