EXPERIMENT:
  name: "w_emb_w_label"
  n_pred_vectors: 2
  n_noise_samples: 3


DATASET:
  names: ["heloc"]
  one_hot: true
  ratio: 0.2
  force: false


CLOUD:
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "neural_net"
