EXPERIMENT:
  name: "w_emb_w_label"
  n_pred_vectors: 1
  n_noise_samples: 2


DATASET:
  names: ["gesture_phase"]
  one_hot: false
  ratio: 0.2


CLOUD:
  path: "gesture_phase_0.2_models.pkl"
  models: ['RandomForestClassifier', 'BernoulliNB', 'CalibratedClassifierCV', 'LinearDiscriminantAnalysis', 'LogisticRegression', 'AdaBoostClassifier', 'ExtraTreesClassifier', 'XGBClassifier', 'LGBMClassifier']

IIM:
  name: "xgboost"
